// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeaManager.API.Data;

#nullable disable

namespace TeaManager.API.Migrations
{
    [DbContext(typeof(TeaManagerDbContext))]
    [Migration("20260509122117_SeedSupplierOrders")]
    partial class SeedSupplierOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeaManager.API.Models.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessRegNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Address = "Lipston House, 42-43 Park Street, London, UK",
                            BrandId = 1,
                            BrandName = "Lipston",
                            BusinessRegNumber = "BRN123445",
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@lipston.com",
                            FoundedYear = 1871,
                            OwnerName = "Jorge Russell",
                            Password = "Lipton@123",
                            Phone = "+44 5-1234-56344"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Address = "TeaCoo Plaza, 343 MG Road, Mumbai, India",
                            BrandId = 2,
                            BrandName = "TeaCoo",
                            BusinessRegNumber = "BRN883456",
                            Country = "India",
                            CreatedAt = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@teacoo.com",
                            FoundedYear = 1950,
                            OwnerName = "Priya Sundar",
                            Password = "Teacoo2345$",
                            Phone = "+91 12-2234-56342"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Address = "LaobanTea Firm, 57 Tea Street, Pu'er City, Yunnan Province, China",
                            BrandId = 3,
                            BrandName = "LaobanTea",
                            BusinessRegNumber = "BRN323595",
                            Country = "China",
                            CreatedAt = new DateTime(2019, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@LaobanTea.com",
                            FoundedYear = 1855,
                            OwnerName = "Li Wei",
                            Password = "LaoBanTea8473$",
                            Phone = "+86 18-7533-34256"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Address = "NortLeaf Plaza, 343 MG Road, Colombo, Sri Lanka",
                            BrandId = 4,
                            BrandName = "NortLeaf",
                            BusinessRegNumber = "BRN833626",
                            Country = "Sri Lanka",
                            CreatedAt = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@NortLeaf.com",
                            FoundedYear = 1950,
                            OwnerName = "Suan Perera",
                            Password = "NortLeaf2334$",
                            Phone = "+94 9384-32848"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Address = "HealthTea Building, 123 Wellness Avenue, New York, USA",
                            BrandId = 5,
                            BrandName = "HealthTea",
                            BusinessRegNumber = "BRN994567",
                            Country = "United States",
                            CreatedAt = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@HealthTea.com",
                            FoundedYear = 2001,
                            OwnerName = "Sarah Johnson",
                            Password = "HealthTea274@q",
                            Phone = "+1 555-123-4567"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Address = "HomeTea House, 456 Tea Lane, Dublin, Ireland",
                            BrandId = 6,
                            BrandName = "HomeTea",
                            BusinessRegNumber = "BRN894567",
                            Country = "Ireland",
                            CreatedAt = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@Hometea.com",
                            FoundedYear = 1900,
                            OwnerName = "Sam Smith",
                            Password = "HomeTea3543$",
                            Phone = "+353 1-234-434256"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Address = "TeaFeast Plaza, 343 MG Road, Kuala Lumpur, Malaysia",
                            BrandId = 7,
                            BrandName = "TeaFeast",
                            BusinessRegNumber = "BRN827456",
                            Country = "Malaysia",
                            CreatedAt = new DateTime(2021, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@Teafeast.com",
                            FoundedYear = 1950,
                            OwnerName = "Ahmad Sandar",
                            Password = "Teafeast2345$",
                            Phone = "+60 12-345-6789"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Address = "TeaForest Plaza, 343 MG Road, Nairobi, Kenya",
                            BrandId = 8,
                            BrandName = "TeaForest",
                            BusinessRegNumber = "BRN883204",
                            Country = "Kenya",
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@TeaForest.com",
                            FoundedYear = 1950,
                            OwnerName = "Samuel Harper",
                            Password = "Teaforest23749@",
                            Phone = "+254 12-365-8890"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Address = "SoftTeabank Building, 123 Financial Avenue, Toronto, Canada",
                            BrandId = 9,
                            BrandName = "SoftTeabank",
                            BusinessRegNumber = "BRN884446",
                            Country = "Canada",
                            CreatedAt = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@softteabank.com",
                            FoundedYear = 1999,
                            OwnerName = "Emily Davis",
                            Password = "SoftTeabank2345$",
                            Phone = "+1 345-763-8901"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Address = "TeaSeason Building, 456 Tea Street, Sydney, Australia",
                            BrandId = 10,
                            BrandName = "TeaSeason",
                            BusinessRegNumber = "BRN885557",
                            Country = "Australia",
                            CreatedAt = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@TeaSeason.com",
                            FoundedYear = 1999,
                            OwnerName = "Michael Johnson",
                            Password = "TeaSeason2345$",
                            Phone = "+61 2-1234-5678"
                        });
                });

            modelBuilder.Entity("TeaManager.API.Models.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HarvestYear")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A refreshing green tea with a crisp flavor and various health benefits.",
                            HarvestYear = 2022,
                            Origin = "Cornwell,United Kingdom",
                            Price = 18.59m,
                            ProductId = 1,
                            ProductName = "Lipston Fresh Green Tea",
                            Stock = 80,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A flavorful black tea from the Assam region of India.",
                            HarvestYear = 2020,
                            Origin = "Assam,India",
                            Price = 20.88m,
                            ProductId = 2,
                            ProductName = "TeaCoo Assam Black Tea",
                            Stock = 80,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2019, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A rich and earthy tea from the Yunnan province of China, famous for its unique fermentation process.",
                            HarvestYear = 2019,
                            Origin = "Yunnan,China",
                            Price = 30.24m,
                            ProductId = 3,
                            ProductName = "LaobanTea Pu'erh Tea",
                            Stock = 20,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A flavorful black tea from the Nuwera Eliya region of Sri Lanka.",
                            HarvestYear = 2021,
                            Origin = "Nuwera Eliya,Sri Lanka",
                            Price = 50.00m,
                            ProductId = 4,
                            ProductName = "NortLeaf Nuwera Premium Black Tea",
                            Stock = 20,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An organic tea blend from the Mauna Kea region of Hawaii, beautifully balanced with floral and earthy notes.",
                            HarvestYear = 2022,
                            Origin = "Hawaii,United States",
                            Price = 25.45m,
                            ProductId = 5,
                            ProductName = "HealthTea Organic Mauna Kea Tea",
                            Stock = 80,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh morning tea with a clear and flavorful taste, perfect for starting your day.",
                            HarvestYear = 2022,
                            Origin = "Dublin,Ireland",
                            Price = 19.59m,
                            ProductId = 6,
                            ProductName = "HomeTea Irish Breakfast Tea",
                            Stock = 150,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000016")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2021, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium earl grey tea with a refreshing citrus flavor and a hint of bergamot, perfect for tea lovers.",
                            HarvestYear = 2021,
                            Origin = "Chiang Mai,Thailand",
                            Price = 15.59m,
                            ProductId = 7,
                            ProductName = "TeaFeast Earl Grey Tea",
                            Stock = 95,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000017")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Blend of fabulous teas from Ostfriesland, Germany.",
                            HarvestYear = 2023,
                            Origin = "Ostfriesland,Germany",
                            Price = 18.95m,
                            ProductId = 8,
                            ProductName = "TeaForest Ostfriesentee",
                            Stock = 80,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000018")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-quality oolong tea from Yunnan, China.",
                            HarvestYear = 2024,
                            Origin = "Yunnan,China",
                            Price = 28.66m,
                            ProductId = 9,
                            ProductName = "SoftTeabank Premium Yunnan Oolong Tea",
                            Stock = 95,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000019")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            BrandId = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fantastic sencha green tea from Japan, with a fresh and grassy flavor.",
                            HarvestYear = 2024,
                            Origin = "Shizuoka,Japan",
                            Price = 33.59m,
                            ProductId = 10,
                            ProductName = "TeaSeason Sencha Green Tea",
                            Stock = 80,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000020")
                        });
                });

            modelBuilder.Entity("TeaManager.API.Models.Domain.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            ContactEmail = "supply@lipston.com",
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+44 6-2346-83745",
                            SupplierId = 1,
                            SupplierName = "Lipston Supplier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            ContactEmail = "supply@kingstone.com",
                            Country = "India",
                            CreatedAt = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+91 12-3334-55384",
                            SupplierId = 2,
                            SupplierName = "Kingstone Supplier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            ContactEmail = "supply@LaobanTeaHub.com",
                            Country = "China",
                            CreatedAt = new DateTime(2019, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+86 18-7532-34253",
                            SupplierId = 3,
                            SupplierName = "LaobanTeaHub Supplier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            ContactEmail = "supply@alonetea.com",
                            Country = "Sri Lanka",
                            CreatedAt = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+94 90-8394-23456",
                            SupplierId = 4,
                            SupplierName = "AloneTea Supplier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            ContactEmail = "supply@TrolTrol.com",
                            Country = "Sri Lanka",
                            CreatedAt = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+94 11-234-5678",
                            SupplierId = 5,
                            SupplierName = "TrolTrol Supplier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            ContactEmail = "supply@HalTea.com",
                            Country = "Kenya",
                            CreatedAt = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+254 11-234-5678",
                            SupplierId = 6,
                            SupplierName = "HalTea Supplier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            ContactEmail = "supply@Thia.com",
                            Country = "Thailand",
                            CreatedAt = new DateTime(2021, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+66 2-123-4567",
                            SupplierId = 7,
                            SupplierName = "Thia Supplier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            ContactEmail = "supply@Funck.com",
                            Country = "Germany",
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+49 30-4568-2345",
                            SupplierId = 8,
                            SupplierName = "Funck Supplier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            ContactEmail = "supply@OolongTeaHub.com",
                            Country = "China",
                            CreatedAt = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+86 10-1234-5678",
                            SupplierId = 9,
                            SupplierName = "OolongTeaHub Supplier"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            ContactEmail = "supply@EdibleTea.com",
                            Country = "Japan",
                            CreatedAt = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+81 3-1234-5678",
                            SupplierId = 10,
                            SupplierName = "EdibleTea Supplier"
                        });
                });

            modelBuilder.Entity("TeaManager.API.Models.Domain.SupplierOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SupplierOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierOrders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000021"),
                            Quantity = 100,
                            Remark = "Initial bulk order from UK",
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000011"),
                            SupplierOrderId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000022"),
                            Quantity = 80,
                            Remark = "Quarterly restock",
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000012"),
                            SupplierOrderId = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000023"),
                            Quantity = 60,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000013"),
                            SupplierOrderId = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            CreatedAt = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000024"),
                            Quantity = 40,
                            Remark = "Premium grade requested",
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000014"),
                            SupplierOrderId = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            CreatedAt = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000025"),
                            Quantity = 120,
                            Remark = "Organic certification verified",
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000015"),
                            SupplierOrderId = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            CreatedAt = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000026"),
                            Quantity = 200,
                            Remark = "Large order for European market",
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000016"),
                            SupplierOrderId = 6
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            CreatedAt = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000027"),
                            Quantity = 70,
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000017"),
                            SupplierOrderId = 7
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            CreatedAt = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000028"),
                            Quantity = 90,
                            Remark = "Express delivery requested",
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000018"),
                            SupplierOrderId = 8
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            CreatedAt = new DateTime(2024, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000029"),
                            Quantity = 110,
                            Remark = "Premium oolong batch",
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000019"),
                            SupplierOrderId = 9
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            CreatedAt = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000030"),
                            Quantity = 150,
                            Remark = "First shipment to Australia",
                            SupplierId = new Guid("00000000-0000-0000-0000-000000000020"),
                            SupplierOrderId = 10
                        });
                });

            modelBuilder.Entity("TeaManager.API.Models.Domain.Product", b =>
                {
                    b.HasOne("TeaManager.API.Models.Domain.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeaManager.API.Models.Domain.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TeaManager.API.Models.Domain.SupplierOrder", b =>
                {
                    b.HasOne("TeaManager.API.Models.Domain.Product", "Product")
                        .WithMany("SupplierOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeaManager.API.Models.Domain.Supplier", "Supplier")
                        .WithMany("SupplierOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TeaManager.API.Models.Domain.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TeaManager.API.Models.Domain.Product", b =>
                {
                    b.Navigation("SupplierOrders");
                });

            modelBuilder.Entity("TeaManager.API.Models.Domain.Supplier", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SupplierOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
